### ISSUE TITLE
Improve DX for enigneers using TypeScript (or type checks)

### ISSUE THREAD

**Issue by chris-miaskowski** [codecept-js/CodeceptJS#1972]
#### What are you trying to achieve?

I'm trying to configure our code base in a way that would reliably warn us about type issues.
In particular I'd like to see correct type errors when I inject more than one page object into my Scenario.

This problem makes the CodeceptJS typings not usable in this specific case.

#### What do you get instead?

Instead, whenever I have more than one page object in the Scenario callback, I immediately get a lot of errors.

### Details

Here is a dummy example (pseud-code):

```js
Scenario('dum-dum', (I, pageA, pageC, pageB) => {
  pageA.doA();
  pageB.doB();
  pageC.doC();
});
```

Note that I have purposefully ordered arguments this way (pageC before pageB).

The following code will work fine in runtime but it will fail at "type check" time. 

**Note** that the following is true even if you don't use TypeScript but simply enable typechecking with the following `jsconfig.json`

```json
{
  "compilerOptions": {
    "checkJs": true
  }
}
```

There reason this code fails comes from the way CodeceptJS injects page objects and how that affects `ICodeceptCallback` type (steps.d.ts).

CodeceptJS uses [fn-args](https://github.com/sindresorhus/fn-args) to inject page objects. It reads function's arguments and it expects exact match between argument name and page object name declared in the config file.

The problem with this approach is that the generated `ICodeceptCallback` expects arguments to be passed in a particular order. In context of this example it could look similar to:

```ts
type ICodeceptCallback = (i?: CodeceptJS.I, current?:any, pageA: PageA, pageB: PageB, pageC: PageC, ...args: any) => void;
```

See that it expects the 3rd argument to be of type `PageA`. However, in runtime (and plain, unchecked javascript) it's totally fine to actually put pageC there instead.

* CodeceptJS version: 2.3.2

## Proposed solution

All those problems would disappear if `ICodeceptCallback` expected just two arguments:

- `I`
- and `custom`

Where `custom` would be an object containing all user-defined page objects, fragments, etc.

This way the order of parameters would no longer matter and type checking would be happy :)

If done this way this example scenario would look like so (I'm using destructuring):

```js
Scenario('dum-dum', (I, { pageA, pageC, pageB }) => {
});
```

and generated `ICodeceptCallback` would become

```ts
type ICodeceptCallback = (i?: CodeceptJS.I, custom?: { pageA?: PageA, pageB?: PageB, pageC?: PageC }) => void;
```

## Workaround

Possible workaround for people with the same problem is to use `inject` function at the top of a testing suite.

Instead of doing

```js
Scenario('x', (I, page) => {})
```

do
```
const { page } = inject();
Scenario('x', (I) => {})
```

Although I don't know whether that will be the same with regards to page object's state.

**Comment by mirao** [comment]
Confirmed with CodeceptJS 2.3.5. At first I was confused why sometimes it works well and sometimes doesn't, therefore thanks for explanation of the issue @chris-miaskowski .

Reliable [autocompletion of methods](https://codecept.io/basics#intellisense) in VSCode works for me for `I` object only because I always pass `I` as the 1st argument in Scenario() callback and it's also the 1st argument in `ICodeceptCallback`.

Autocompletion for page objects works well only if order of page objects arguments in Scenario() matches order in `ICodeceptCallback`.

The workaround seems to be functional for me. I tried it with one of my tests where I injected all page objects globally and deleted them from callback arguments in each Scenario().

**Comment by chris-miaskowski** [comment]
@mirao I ended up rewriting the whole e2e suite to TypeScript and using the following approach:

```ts
// import your pageObject like any other regular module
// the benefit of using this approach is that TypeScript will automatically resolve all types and you will
// be able to navigate to functions of that object (vs to the "types" definition file).
import { pageObject } from '@myPackage/x/y/z/pageObject';
import { fragment } from '@myPackage/x/y/z/fragment;

// do not inject pageObject here
const { I } = inject();

Scenario('Description', () => {
  pageObject.x();
  fragment.y();
  I.see('Z');
});
```

With that, all autocompletion works great, I don't have to regenerate types and it has many other advantages. I would suggest that TypeScript should be the default way of using codecept. I kind of felt that the framework's IoC does not add much value if `require` or `import` is used properly.

Anyways, glad that my workaround was useful.

**Comment by mirao** [comment]
@chris-miaskowski This is exactly what I'm missing in CodeceptJS - to see more details (e.g. method's/properties description from JSDoc annotation) when hovering on page object's method/properties and navigation to source of method/property using `Ctrl + Click` (instead of navigation to `steps.d.ts`).

Similarly as you described, If I use e.g. `const loginPage = require("./pages/Login");` then expected IntelliSense works for me on `loginPage`'s methods/properties in scenario.
A little disadvantage is that `require` must be specified in every test (instead of centralized "include" in `codecept.conf.js`).

Similar approach is in [PHP Codeception](https://codeception.com/docs/06-ReusingTestCode.html#PageObjects) (that I'm using for some projects) where in scenario you specify path to page object using namespace convention and then IntelliSense work (I'm using a VSCode extension for it)

@chris-miaskowski: I don't have any experience with TypeScript tests. I thought that `import` and `export` is experimental in NodeJS so far. Or does `import { pageObject } from '@myPackage/x/y/z/pageObject';` work different way?

**Comment by mirao** [comment]
OK, something about CodeceptJS TypeScript tests is [here](https://stackoverflow.com/questions/57505864/how-can-we-use-typescript-with-codeceptjs-for-testing-framework).
It uses [ts-node](https://codecept.io/configuration/#require), maybe I'll give it a try.

**Comment by chris-miaskowski** [comment]
> A little disadvantage is that `require` must be specified in every test (instead of centralized "include" in `codecept.conf.js`).

If you are using VS Code then this shouldn't be a problem. E.g. if you move a file VS Code will usually refactor all `require` for you. Regardless of whether it's TS or JS. I don't see any advantage of the centralized import, to be honest ;)

I mean, all other code we write uses standard `import` and `require`. Dependency Injection makes sense if you want to overwrite an instance of something in runtime by configuration - otherwise, I think it's a bit of an overkill ;) (if I were the author of this framework I would probably get rid of the whole DI thing :P )

> 
> @chris-miaskowski: I don't have any experience with TypeScript tests. I thought that `import` and `export` is experimental in NodeJS so far. Or does `import { pageObject } from '@myPackage/x/y/z/pageObject';` work different way?

TypeScript 'transpiles' you code to JavaScript. In tsconfig.json you can specify what will the `import` resolve to. With CodeceptJS the best option is to set the module resolution to `commonjs`. When TS files get transpiled all `imports` will basically get converted to `require`.

The link you found should get you to the right direction. Yes, one way to use it is to run your code with `ts-node`.

I think I used this https://github.com/elukoyanov/codecept-typescript-example as a guide and tweaked it a bit. I now have a fully TypeScriped codeceptjs suite will all modern fancy features enabled. One nice bonus is that I can share the company styleguides and reuse some backend GraphQL queries written in TypeScript :] 

Have a good Sunday and good luck!

**Comment by mirao** [comment]
Great. Thanks for looking into it @chris-miaskowski. BTW I didn't know about the refactoring feature in VSCode when moving/renaming file with module. It really works!

**Comment by mirao** [comment]
I've just upgraded to [CodeceptJS 2.3.6](https://codecept.io/changelog#236) and run `npx codeceptjs def`.

Now I don't need to use `const loginPage = require("./pages/Login");` to get correct IntelliSense (https://github.com/Codeception/CodeceptJS/issues/1972#issuecomment-560108412), because the page object definition is already imported in `steps.d.ts`, e.g.:
``` js
type loginPage = typeof import('./pages/Login.js');
```
So now when I'm clicking on a method of loginPage, it navigates to source of the method as expected.

Of course the issue #1972 is blocking autocomplete/intellisense in case of multiple page objects passed in random order.
